# Supabase Configuration

[functions.enhance-prompt]
verify_jwt = false

[functions.make-server-e52adb92]
verify_jwt = false

[functions.mint-token]
enabled = true
verify_jwt = true
import_map = "./functions/mint-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mint-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mint-token/*.html" ]

[functions.redeem-token]
enabled = true
verify_jwt = true
import_map = "./functions/redeem-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/redeem-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/redeem-token/*.html" ]
